CC ?= cc
CFLAGS ?= -Wall -std=c99 -g
PROGNAME := myprog
SRCS := main.c # add more c source files here, separate by spaces

prefix ?= /usr/local

OBJS := $(SRCS:.c=.o)

# this is a target specific variable declaration. These values 
# will be appended (+=) to the CFLAGS variable if the 'pedantic'
# target is invoked. e.g. 'make pedantic'
pedantic: CFLAGS += -Wextra -pedantic -D_XOPEN_SOURCE=700

all: $(PROGNAME)

# for strict standards compliance. Strive for 'make pedantic' 
# to run without warnings
pedantic: $(PROGNAME)
 
$(PROGNAME): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^

# includes any .P files generated by auto-dependency 
# generator below
-include $(OBJS:.o=.P)

# compilation and auto-dependency generation 
# in one step. Works with gcc and clang
# See http://mad-scientist.net/make/autodep.html
%.o: %.c
	$(CC) $(CFLAGS) -MMD -c -o $@ $<
	@cp $*.d $*.P; \
	sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
	    -e '/^$$/ d' -e 's/$$/ :/' < $*.d >>$*.P; \
	rm -f $*.d

.PHONY: clean
clean:
	rm -f *.o *.P $(PROGNAME)

install:
	cp $(PROGNAME) $(prefix)/bin
